deploy/pi.cfg                            etc/privacyidea/
deploy/apache/privacyideaapp.wsgi        etc/privacyidea/

deploy/privacyIDEA.png			var/www/icon/

# join script
deploy/usr/lib/univention-install/12privacyidea.inst usr/lib/univention-install/
deploy/usr/lib/univention-uninstall/12privacyidea.uinst usr/lib/univention-uninstall/

# apache config
deploy/apache/sites-available/privacyidea.conf	etc/apache2/sites-available/

# Add license library
deploy/privacyidea-patch/lib/subscription.py		opt/privacyidea/privacyidea-venv/lib/python2.7/site-packages/privacyidea/lib/
